apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-deps-configmap
  namespace: {{ .Values.namespace }}
data:
  requirements.txt: |
    {{ .Files.Get "src/requirements.txt"  | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
  namespace: {{ .Values.namespace }}
data:
  aws-vpc-metrics-exporter.py: |
    {{ .Files.Get "src/main.txt"  | indent 4 }}