apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      serviceAccountName: {{ .Values.deployment.serviceAccountName }}
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.deployment.image }}
          command: ["/bin/bash", "-c"]
          args:
            - |
              pip install -r /app/requirements.txt && python /app/aws-vpc-metrics-exporter.py
          resources:
            limits:
              memory: "256Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
          ports:
            - containerPort: 9106
          env:
            - name: AWS_REGION
              value: {{ .Values.aws.region }}
            {{- if ne .Values.aws.accessKeyID "<AWS_ACCESS_KEY>" }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.aws.accessKeyID }}
            {{- end }}
            {{- if ne .Values.aws.secretAccessKey "<AWS_ACCESS_SECRET>" }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.aws.secretAccessKey }}
            {{- end }}
          volumeMounts:
            - name: python-script-volume
              mountPath: /app/aws-vpc-metrics-exporter.py
              subPath: aws-vpc-metrics-exporter.py
            - name: dependencies-volume
              mountPath: /app/requirements.txt
              subPath: requirements.txt
      volumes:
        - name: python-script-volume
          configMap:
            name: {{ .Values.appName }}-configmap
        - name: dependencies-volume
          configMap:
            name: {{ .Values.appName }}-deps-configmap