appName: aws-vpc-metrics-exporter

namespace: monitoring

aws:
  region: eu-west-1
  accessKeyID: <AWS_ACCESS_KEY>
  secretAccessKey: <AWS_ACCESS_SECRET>

deployment:
  replicas: 1
  serviceAccountName: default
  image: python:3.8
